# The naming layout for stacked mobs. Use the {QTY} and {TYPE} tags, along with normal colour codes to customise the in game display.
stack-naming: '&e&l{QTY}X &6&l{TYPE}'

# How far around the mob should the plugin check for mobs to stack to?
stack-range:
    x: 5
    y: 2
    z: 5

# How many seconds after a mob spawns should the plugin check for mobs to stack to?
# The higher the number, the more work for the server to do. Keep this rather low. In SECONDS NOT TICKS.
# Set to 0 to only try stack on spawn. Set to -1 to never stop trying to stack (Possibly lag inducive for larger number of mobs (1000+).
seconds-to-try-stack: 5

# If false, named mobs will not stack, meaning pets are protected.
stack-custom-named-mobs: false

# If false mobs will stack regardless of age (Baby or adult)
stack-by-age: true

# False means that animals on a leash will not stack.
stack-leashed-animals: false

# Upon leashing an entity, should the full stack be leashed, or just one?
leash-whole-stack: false


# Protect tamed animals from being stacked on?
protect-tamed: true

# If a creeper stack explodes, should the whole stack die?
exploding-creeper-kills-stack: true

# Should a creepers explosion be made larger if the full stack explodes? exploding-creeper-kills-stack: must be true for this to work.
magnify-stack-explosion:
    enable: false
    max-creeper-explosion-size: 5

# If true mobs will stack through walls.
stack-through-walls: false

# Should coloured mobs, like sheep, be stacked separately?
separate-stacks-by-color: true

# Should sheep be separated based on whether they are shorn or not?
separate-by-sheared: true

# If a burning stack dies, should the remaining burn time for the previous mob be carried on to the next?
carry-over-fire:
  enabled: false
  # If star-new-burn is true, it will be as if the next mob in the stack has been set on fire again, otherwise it will only burn for the remaining
  # time of the previous mob.
  start-new-burn: false
  # When a new burn starts after a stack dies, how many ticks should it burn for? 100 ticks is 5 seconds.
  new-burn-ticks: 100

# What should the max stack size be for certain mobs? If a mob isn't listed, the stack size isn't limied. Add Mobs as shown below to create a stack limit.
max-stack-sizes:
    IRON_GOLEM: 10

#This will limit the number of mobs in a chunk by their type. A stack of 10 counts as 10 mobs.
max-mobs-per-chunk:
    PIG: 100

# List worlds that no mobs will ever stack in. Write ALL world names in ONLY lower case.
blacklist-world:
    - example-world

# For which spawn methods should mobs be nerfed? Nerfed mobs can still be moved, but will not target or attack a player.
mob-nerfing:
    - SPAWNER

# Stacks from these spawn methods will not give any mcMMO experience
no-mcmmo-exp:
    - SPAWNER
    - SPAWNER_EGG

# Leaving this true will clear mob stacks if you use ClearLag(g)
clear-lag: true

# Should mobs always stack towards the ground? Useful for flying mobs, like blazes and ghasts.
stack-mobs-down:
    enable: true
    mob-types:
        - BLAZE
        - GHAST

# If a stack of mobs fall off should the full stack die, or just one mob in the stack?
# All damage causes can be found at https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/entity/EntityDamageEvent.DamageCause.html
kill-whole-stack-on-death:
    enable: true
    multiply-loot: true
    looting: false
    reasons:
      - FALL

# Mobs marked with true WILL attempt to stack. Mobs spawned by building (Golems and Wither) are a bit buggy, so it is suggested to leave them false.
stack-mob-type:
    BAT: true
    BLAZE: true
    CAVE_SPIDER: true
    CHICKEN: true
    COW: true
    CREEPER: true
    ENDERMAN: true
    ENDERMITE: true
    GHAST: true
    GIANT: true
    GUARDIAN: true
    HORSE: true
    IRON_GOLEM: true
    MAGMA_CUBE: true
    MUSHROOM_COW: true
    OCELOT: true
    PIG: true
    PIG_ZOMBIE: true
    RABBIT: true
    SHEEP: true
    SILVERFISH: true
    SKELETON: true
    SLIME: true
    SNOWMAN: true
    SPIDER: true
    SQUID: true
    VILLAGER: true
    WITCH: true
    WITHER: true
    WOLF: true
    ZOMBIE: true
    POLAR_BEAR: true

# Spawn methods marked with true WILL attempt to stack. CUSTOM is mobs spawned by plugins - Including this one. Certain features require CUSTOM to be left true.
# Plugin will be effected is CUSTOM is set to false.
# It is suggested to leave BUILD spawn methods as false as it is able to be exploited in the right situation
stack-spawn-method:
    SPAWNER_EGG: true
    SPAWNER: true
    BREEDING: false
    BUILD_IRONGOLEM: false
    BUILD_SNOWMAN: false
    BUILD_WITHER: false
    CHUNK_GEN: false
    CURED: false
    CUSTOM: true
    DISPENSE_EGG: true
    EGG: true
    INFECTION: false
    JOCKEY: false
    LIGHTNING: false
    MOUNT: false
    NATURAL: false
    OCELOT_BABY: false
    SLIME_SPLIT: false
    NETHER_PORTAL: true
    MYTHIC_MOBS: false